export const SUCCESS_MESSAGE = {
	USER_REGISTERED: "User registered successfully.",
	USER_LOGGED_IN: "User logged in successfully.",
	USER_UPDATED: "User updated successfully.",
	USER_DELETED: "User deleted successfully.",
	USER_CREATED: "User created successfully.",
	USER_VERIFIED: "User verified successfully.",
	USER_PASSWORD_RESET: "Password reset successfully.",
	USER_PASSWORD_CHANGED: "Password changed successfully.",
	USER_LOGGED_OUT: "User logged out successfully.",
	ANALYTICS_FETCHED: "Analytics data fetched successfully.",
	ACHIEVEMENTS_FETCHED: "Achievements fetched successfully.",
	ACHIEVEMENT_EARNED: "Achievement earned successfully.",
	ACHIEVEMENT_PROGRESS_UPDATED: "Achievement progress updated successfully.",
	ACHIEVEMENT_CHECKED: "Achievements checked successfully.",
	ACHIEVEMENT_CREATED: "Achievement created successfully.",
	ACHIEVEMENT_UPDATED: "Achievement updated successfully.",
	ACHIEVEMENT_DELETED: "Achievement deleted successfully.",
	ACHIEVEMENT_REWARDED: "Achievement rewarded successfully.",
	ACHIEVEMENT_UNLOCKED: "Achievement unlocked successfully.",
	ACHIEVEMENT_REWARDED: "Achievement rewarded successfully.",
};
